name: RSGB API Snapshot
permissions:
  contents: write
on: 
  schedule:
    - cron: "0 */3 * * *"
jobs:
  Snapshot-Rsgb-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Fetch data
        run: |
          curl --silent https://api-beta.rsgb.online/all/systems | jq > all-systems.json
      - name: Commit data
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'm0lte@users.noreply.github.com'
          git add all-systems.json
          git commit -am "Automated commit" || echo "No change"
          git push
